language: objective-c
   
osx_image: xcode8.0
   
script: 
   xctool -project ButtonBackgroundColor.xcodeproj -scheme ButtonBackgroundColor build -scheme ButtonBackgroundColorTests test -sdk iphonesimulator
