language: objective-c
   
osx_image: xcode7.3
   
script: 
   xctool -project ButtonBackgroundColor.xcodeproj -scheme ButtonBackgroundColor build -scheme ButtonBackgroundColorTests test -sdk iphonesimulator
