language: objective-c
   
osx_image: xcode7.2
   
script: 
   xctool -project ButtonBackgroundColor.xcodeproj -scheme ButtonBackgroundColor build -scheme ButtonBackgroundColorTest test -sdk iphonesimulator
